"""
Step 8: Formatter.

Applies platform-specific structural rules from platform_rules.json.
In real mode, uses an LLM to apply LinkedIn formatting rules and returns a
structured FormattedContent. In mock mode, returns a deterministic result.

If revision_hint is provided (retry path), it is prepended to the system
prompt so the LLM applies the specific fix before re-formatting.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from llm.client import chat_completion
from config import settings
from schemas.brand_profile import BrandProfile
from schemas.content_brief import ContentBrief
from schemas.formatted_content import FormattedContent, LinkedInContent
from schemas.strategy_brief import StrategyBrief
from agents._utils import parse_json_object, utc_now_iso

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_rules() -> dict:
    path = Path(__file__).resolve().parent.parent / "config" / "platform_rules.json"
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def _normalize_hashtag(tag: str) -> str:
    tag = tag.strip()
    if not tag:
        return tag
    return tag if tag.startswith("#") else f"#{tag}"


# ---------------------------------------------------------------------------
# Mock
# ---------------------------------------------------------------------------

def _mock_linkedin(
    raw_copy: str,
    content_brief: ContentBrief,
    retry_count: int,
    revision_hint: str | None,
) -> FormattedContent:
    lines = [x.strip() for x in raw_copy.splitlines() if x.strip()]
    hook_raw = lines[0] if lines else "Most engineering teams don't have a project management problem."
    hook = hook_raw[:180]

    body_lines = lines[1:] if len(lines) > 1 else ["Content generated by Genate pipeline."]
    body = "\n\n".join(body_lines)

    hashtags = ["#engineeringmanagement", "#softwaredevelopment", "#productivity"]
    full_post = f"{hook}\n\n{body}\n\n{' '.join(hashtags)}"

    return FormattedContent(
        run_id=content_brief.run_id,
        org_id=content_brief.org_id,
        created_at=utc_now_iso(),
        platform="linkedin",
        linkedin_content=LinkedInContent(
            hook=hook,
            body=body,
            hashtags=hashtags,
            full_post=full_post,
        ),
        retry_count=retry_count,
        revision_hint_applied=revision_hint,
    )


def _mock_twitter(
    raw_copy: str,
    content_brief: ContentBrief,
    retry_count: int,
    revision_hint: str | None,
) -> FormattedContent:
    tweets = [x.strip() for x in raw_copy.split("\n\n") if x.strip()]
    # Pad to minimum 4 if needed
    while len(tweets) < 4:
        tweets.append("More details to come.")
    tweets = tweets[:8]
    tags = ["#saas"]
    tweets[-1] = f"{tweets[-1]} {' '.join(tags)}".strip()
    return FormattedContent(
        run_id=content_brief.run_id,
        org_id=content_brief.org_id,
        created_at=utc_now_iso(),
        platform="twitter",
        twitter_content={
            "tweets": tweets,
            "tweet_char_counts": [len(t) for t in tweets],
            "hashtags": tags,
        },
        retry_count=retry_count,
        revision_hint_applied=revision_hint,
    )


# ---------------------------------------------------------------------------
# LinkedIn real-mode system prompt
# ---------------------------------------------------------------------------

_LINKEDIN_SYSTEM = (
    "You are a content formatter. Apply LinkedIn platform rules exactly.\n\n"
    "LinkedIn rules:\n"
    "- Hook must be a standalone statement in the first 180 characters\n"
    "- 3-5 hashtags at end only, never inline in the body\n"
    "- Short paragraphs with a blank line between each\n\n"
    "Return ONLY valid JSON with these exact fields:\n"
    "  hook: the standalone opening line (max 180 chars)\n"
    "  body: the full post body excluding the hook line and hashtags\n"
    "  hashtags: list of 3-5 hashtags, each starting with #\n"
    "  full_post: hook + two newlines + body + two newlines + hashtags space-joined"
)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def run(
    raw_copy: str,
    content_brief: ContentBrief,
    strategy_brief: StrategyBrief,
    brand_profile: BrandProfile,
    revision_hint: str | None = None,
    retry_count: int = 0,
) -> FormattedContent:
    platform = content_brief.platform

    # ── Mock path ────────────────────────────────────────────────────────────
    if settings.MOCK_MODE:
        if platform == "linkedin":
            return _mock_linkedin(raw_copy, content_brief, retry_count, revision_hint)
        if platform == "twitter":
            return _mock_twitter(raw_copy, content_brief, retry_count, revision_hint)
        # Fallback for other platforms in mock mode
        lines = [x.strip() for x in raw_copy.splitlines() if x.strip()]
        hook = lines[0][:180] if lines else "SaaS content pipeline output."
        body = "\n\n".join(lines[1:]) if len(lines) > 1 else raw_copy
        hashtags = ["#saas", "#marketing", "#content"]
        return FormattedContent(
            run_id=content_brief.run_id,
            org_id=content_brief.org_id,
            created_at=utc_now_iso(),
            platform="linkedin",  # type: ignore[arg-type]
            linkedin_content=LinkedInContent(
                hook=hook,
                body=body,
                hashtags=hashtags,
                full_post=f"{hook}\n\n{body}\n\n{' '.join(hashtags)}",
            ),
            retry_count=retry_count,
            revision_hint_applied=revision_hint,
        )

    # ── Real mode: LinkedIn ──────────────────────────────────────────────────
    if platform == "linkedin":
        system = _LINKEDIN_SYSTEM

        # Prepend revision instruction if this is a retry
        if revision_hint:
            system = (
                f"REVISION REQUIRED: {revision_hint}\n"
                "Apply this specific fix to the copy below before formatting.\n\n"
                + system
            )

        user_msg = f"Format this copy for LinkedIn:\n\n{raw_copy}"

        raw_response = chat_completion(
            [
                {"role": "system", "content": system},
                {"role": "user", "content": user_msg},
            ],
            temperature=0,
        )

        try:
            data = parse_json_object(raw_response)
        except ValueError:
            # Fallback: parse raw_copy mechanically
            logger.warning("Formatter: LLM returned non-JSON; falling back to mechanical parse")
            return _mock_linkedin(raw_copy, content_brief, retry_count, revision_hint)

        # Normalise hashtags
        hashtags_raw = data.get("hashtags", [])
        if isinstance(hashtags_raw, str):
            hashtags_raw = hashtags_raw.split()
        hashtags = [_normalize_hashtag(h) for h in hashtags_raw if h]

        # Clamp hashtag count
        if len(hashtags) < 3:
            hashtags += ["#saas", "#marketing", "#b2b"][: 3 - len(hashtags)]
        hashtags = hashtags[:5]

        hook = str(data.get("hook", "")).strip()[:180]
        if not hook:
            lines = [x.strip() for x in raw_copy.splitlines() if x.strip()]
            hook = lines[0][:180] if lines else "SaaS marketing copy."

        body = str(data.get("body", "")).strip()
        if not body:
            body = raw_copy

        full_post = str(data.get("full_post", "")).strip()
        if not full_post:
            full_post = f"{hook}\n\n{body}\n\n{' '.join(hashtags)}"

        return FormattedContent(
            run_id=run_id,
            org_id=org_id,
            created_at=utc_now_iso(),
            platform="linkedin",
            linkedin_content=LinkedInContent(
                hook=hook,
                body=body,
                hashtags=hashtags,
                full_post=full_post,
            ),
            retry_count=retry_count,
            revision_hint_applied=revision_hint,
        )

    # ── Real mode: Twitter (programmatic — no LLM needed) ───────────────────
    if platform == "twitter":
        tweets = [x.strip() for x in raw_copy.split("\n\n") if x.strip()]
        while len(tweets) < 4:
            tweets.append("More details to come.")
        tweets = tweets[:8]
        tags = [_normalize_hashtag("saas")]
        tweets[-1] = f"{tweets[-1]} {' '.join(tags)}".strip()
        return FormattedContent(
            run_id=run_id,
            org_id=org_id,
            created_at=utc_now_iso(),
            platform="twitter",
            twitter_content={
                "tweets": tweets,
                "tweet_char_counts": [len(t) for t in tweets],
                "hashtags": tags,
            },
            retry_count=retry_count,
            revision_hint_applied=revision_hint,
        )

    # ── Real mode: Instagram ─────────────────────────────────────────────────
    if platform == "instagram":
        clean = raw_copy.strip()
        preview = clean[:125]
        body_text = clean[125:]
        hashtags = [_normalize_hashtag(f"tag{i}") for i in range(1, 21)]
        full_caption = f"{preview}\n\n{body_text}\n\n\n\n\n{' '.join(hashtags)}"
        return FormattedContent(
            run_id=run_id,
            org_id=org_id,
            created_at=utc_now_iso(),
            platform="instagram",
            instagram_content={
                "preview_text": preview,
                "body": body_text,
                "hashtags": hashtags,
                "full_caption": full_caption,
            },
            retry_count=retry_count,
            revision_hint_applied=revision_hint,
        )

    # ── Real mode: Blog (programmatic) ──────────────────────────────────────
    body_text = raw_copy
    seo = content_brief.seo_keyword or "saas marketing"
    words = body_text.split()
    if seo.lower() not in " ".join(words[:100]).lower():
        body_text = f"{seo} helps teams produce brand-consistent content.\n\n{body_text}"
    return FormattedContent(
        run_id=run_id,
        org_id=org_id,
        created_at=utc_now_iso(),
        platform="blog",
        blog_content={
            "title": "SaaS Content Systems That Scale",
            "meta_title": "SaaS content system for faster GTM execution",
            "meta_description": (
                "Learn how SaaS teams use strategy-first workflows to generate "
                "brand-consistent content faster while grounding every claim in proof."
            ),
            "body": body_text,
            "word_count": len(body_text.split()),
            "internal_link_placeholders": ["[INTERNAL_LINK: brand messaging strategy]"],
            "seo_keyword": seo,
        },
        retry_count=retry_count,
        revision_hint_applied=revision_hint,
    )
