"""
schemas/research_proof_point.py
Genate — ResearchProofPoint Schema

Produced by: Research agent (Step 3.5)
Consumed by: ProductKnowledge.research_proof_points, Strategy agent (Step 5)
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, field_validator


class ResearchProofPoint(BaseModel):
    """
    A third-party research stat relevant to the brand's product
    category and pain points. Extracted from real fetched content —
    never generated by the LLM.

    Flows into ProductKnowledge.research_proof_points and is
    available to the Strategy agent alongside brand proof points.
    """

    text: str
    # The exact stat as it appears in the source.
    # e.g. "75% of B2B buyers consult AI before contacting a vendor"
    # Must be extractable verbatim from source_content_snippet.

    source_name: str
    # Publication or organisation name.
    # e.g. "Gartner", "McKinsey", "HubSpot", "Forrester"

    source_url: str
    # The actual URL the stat was extracted from.

    publication_year: int | None = None
    # Year of publication if determinable from content.

    relevance_reason: str
    # One sentence: why this stat matters for this product category.

    proof_type: Literal[
        "industry_stat",   # market size, adoption rates, trends
        "survey_finding",  # buyer behaviour, team habits
        "academic",        # peer-reviewed research
        "report",          # analyst report (Gartner, Forrester etc.)
        "news_stat",       # stat from reputable news coverage
    ]

    credibility_tier: Literal["tier_1", "tier_2", "tier_3"] = "tier_2"
    # tier_1: Gartner, Forrester, McKinsey, academic peer-reviewed
    # tier_2: HubSpot, Salesforce, reputable industry publications
    # tier_3: blogs, vendor-produced reports, news articles

    source_content_snippet: str = ""
    # Raw text from which the stat was extracted.
    # Used for validation only — excluded from pipeline JSON output.

    @field_validator("text")
    @classmethod
    def text_not_empty(cls, v: str) -> str:
        if not v or len(v.strip()) < 10:
            raise ValueError("ResearchProofPoint.text must be at least 10 chars")
        return v.strip()

    @field_validator("source_url")
    @classmethod
    def url_has_scheme(cls, v: str) -> str:
        if not v.startswith(("http://", "https://")):
            raise ValueError("source_url must start with http:// or https://")
        return v
